engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CyclomaticComplexity:
        enabled: true
        reportLevel: 13
      # Disable some checks
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
  radon:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- docs/**/*
- tests/**/*
- vendor/**/*
