engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    #config:
    #  file_extensions: "php"
    #  rulesets: "unusedcode,codesize,naming,optional_relative_path_to_custom_ruleset.xml"
    exclude_fingerprints:
      - 9d462b7c90c564bf28007ee399340fad # table() NPath is too complex.
    checks:
      CyclomaticComplexity:
        enabled: true
        reportLevel: 20
      ExcessiveClassComplexity:
        maximum: 80
      Design/NpathComplexity:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false

  radon:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- docs/**/*
- tests/**/*
- vendor/**/*
