language: php
php:
    - '5.5'
    - '7.0'

before_script:
    - composer install

after_script:
    - vendor/bin/test-reporter

notifications:
    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change
