language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'

cache:
  directories:
    - $HOME/.composer/cache

services:
    - mysql

before_script:
    - composer self-update
    - composer install --no-ansi
    - mysql -e 'create database dsql_test;'

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]]; then NC="--no-coverage"; fi
    - ./vendor/bin/phpunit $NC
    - ./vendor/bin/phpunit --configuration phpunit-mysql.xml $NC

after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then vendor/bin/test-reporter; fi

notifications:
    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change
    email: false
