language: php
php:
    - '5.5'
    - '7.0'

services:
    - mysql

before_script:
    - composer install

after_script:
    - vendor/bin/test-reporter

script:
    - phpunit
    - phpunit --configuration phpunit-mysql.xml
    - phpunit --configuration phpunit-sqlite.xml

notifications:
    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change
